### ISSUE TITLE
CoTuning execution result problem

### ISSUE THREAD

**Issue by sksksk1748** [thuml/CoTuning#1]
My environment :
```
CUDA 10.1
python 3.7.10
pytorch == 1.7.1
torchvision == 0.8.2
torchaudio == 0.7.2
scikit-learn == 0.24.1
numpy == 1.20.1
argparse == 1.4.0 
tqdm == 4.59.0
```

Dataset Downloadlink : 
https://drive.google.com/file/d/1hbzc_P1FuxMkcabkgn9ZKinBwW683j45/view

Offical CUB-200-2011 dataset ( 001. ~ 200. )
![image](https://user-images.githubusercontent.com/45991763/110583747-1e230600-81a9-11eb-8c10-9542199ba3af.png)

My CUB-200-2011 dataset directory architecture :
```
CoTung
├── data/
│   └── finetune/ 
│       └── cub200/ 
│           ├── test/
│           │   └── test/
│           │       └── ... (151. ~ 200. image folder)
│           ├── train/
│           │   └── train/
│           │       └── ... (001. ~ 120. image folder)
│           └──  val/
│               └── val/
│                   └── ... (121. ~ 150. image folder)
├── module/
├── train.py
└── ...
```

My Quick Start : 
```python
$ python train.py --gpu 0 --data_path ./data/finetune/cub200/ --class_num 200 --batch_size 32
```

Result : 
![image](https://user-images.githubusercontent.com/45991763/110575606-1c057b00-819a-11eb-852e-cc0dc217fdbe.png)

How to solve ?
Thanks !

**Comment by Lanxiaozhi** [comment]
I noticed that your directory architecture is not correct, it should be like this (just remove the redundant layers):
```
CoTung
├── data/
│   └── finetune/ 
│       └── cub200/ 
│           ├── test/
│           │       └── ... (about 200 image folders)
│           ├── train/
│           │       └── ... (about 200 image folders)
│           └──  val/
│                   └── ... (about 200 image folders)
├── module/
├── train.py
└── ...
```
The split of the dataset should be based on all data rather than category (each folder should contain all 200 categories).

**Comment by Lanxiaozhi** [comment]
@sksksk1748 
I noticed that your directory architecture is not correct, it should be like this (just remove the redundant layers):
```
CoTung
├── data/
│   └── finetune/ 
│       └── cub200/ 
│           ├── test/
│           │       └── ... (about 200 folders)
│           ├── train/
│           │       └── ... (about 200 folders)
│           └──  val/
│                   └── ... (about 200 folders)
├── module/
├── train.py
└── ...
```
The split of the dataset should be based on all data rather than category (each folder should contain about 200 categories).

**Comment by youkaichao** [comment]
@sksksk1748 Where do you get the "official" split?

**Comment by sksksk1748** [comment]
@Lanxiaozhi Great !
@youkaichao 
After I downloaded the dataset from the official, I divided the dataset by myself
To be honest, this is not a wise method, because it is difficult to restore the results of your experiment.
I hope you can provide information on how the datasets of CUB-200-2011, Stanford Cars, and FGVC Aircraft are divided on the path.
By the way, after downloading the COCO70 dataset, the images in it are displayed abnormally, is it correct?
In my opinion, should be able to see what this picture is.

**Comment by youkaichao** [comment]
@sksksk1748 what do you mean by "after downloading the COCO70 dataset, the images in it are displayed abnormally"? Can you provide some showcases? In my server, the images are displayed normally :)

**Comment by youkaichao** [comment]
The problem of "directory architecture" has been resolved and so this issue will be closed. But you are free to continue the discussion on COCO70 and we are glad to help you.
