### ISSUE TITLE
NLP NER support

### ISSUE THREAD

**Issue by Daemonyz** [thuml/CoTuning#2]
Is there any support for NLP NER tasks? 
How could we reproduce NER experiments using BERT + Co-Tuning.
Thanks.

**Comment by yushengsu-thu** [comment]
Could you please release the codes of 5.4 Named Entity Recognition and 5.5 Ablation Study in the paper please?

**Comment by youkaichao** [comment]
Hi, NER experiments using BERT is taken from huggingface transformers. You can use their code and Co-Tuning can be easily plugged in. In the future, Co-Tuning will be integrated into the [transfer learning library](https://github.com/thuml/Transfer-Learning-Library), stay tuned if you want official implementation!
