### ISSUE TITLE
Reproducibility issue

### ISSUE THREAD

**Issue by korawat-tanwisuth** [thuml/CoTuning#3]
Do you mind sharing the exact split for each dataset for reproducibility? It would be nice if you can tar the file and put it in a drive for download. While you have roughly specified the architecture and the data splitting for COCO dataset, the data splittings for other datasets are not provided.  Thanks in advance.

**Comment by youkaichao** [comment]
We do not own the copyright of these datasets, so we cannot release the tar file.

For the COCO-70 dataset we create, we have zipped the file to a web drive and you can download it directly.
