### ISSUE TITLE
 How to determine the number of iter？

### ISSUE THREAD

**Issue by shihaobai** [thuml/CoTuning#4]
Very nice job!  I wonder how to determine the number of iteraitons to better reproduce the result.  Is it determined according to the size of the data set and the fixed number of epochs?   Thank you very much ！

**Comment by youkaichao** [comment]
Because the datasets we use (CUB-200-2011 / Stanford Cars / FGVC Aircraft) have roughly the same size, so we use a fixed number (i.e. 9500) of iterations in the code.
We recommend to adjust the number of iteraitons according to the size of the data set and the fixed number of epochs.

**Comment by shihaobai** [comment]
Thank you for your help, I trained the model 150 epoches for each downstrean dataset. It also can get reasonable results.
